[package]
name = "agc045_a"
version = "0.1.0"
authors = ["Hiromi Ayase <hiromi.ayase@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = ">=0.3.6" }
